tag_locations:
  [
    {id: 1, x: 0.491, y: -1.468, z: 0.118, qx: 0.028, qy: 0.664, qz: 0.747, qw: -0.016},
    {id: 2, x: 3.674, y: 6.360, z: 0.153, qx: 0.670, qy: -0.023, qz: -0.013, qw: 0.742},
    {id: 4, x: 0.583, y: 2.186, z: 0.161, qx: 0.670, qy: -0.013, qz: -0.038, qw: 0.741},
    {id: 7, x: 1.191, y: 0.568, z: 0.086, qx: 0.523, qy: -0.390, qz: -0.455, qw: 0.606},
    # {id: 7, x: 0.0, y: 0.0, z: 0.0, qx: 0.0, qy: 0.0, qz: 0.0, qw: 1.0},
    {id: 8, x: 0.873, y: -1.957, z: 0.086, qx: 0.055, qy: 0.658, qz: 0.749, qw: 0.063}
  ]
max_detection_dist: 2.0
max_linear_vel_x: 0.5     # max: 1.0
max_angular_vel_z: 0.5      # max: 2.0
xy_tolerance: 0.0
yaw_tolerance: 0.0
update_frequency: 5.0
debug: 0