tag_locations:
  [
    {id: 1, x: 0.456458, y: -1.414853, z: 0.094037, qx: -0.020081, qy: -0.648789, qz: -0.760375, qw: 0.022354},
    {id: 2, x: 3.638085, y: 6.377855, z: 0.094940, qx: 0.652064, qy: -0.060059, qz: -0.059957, qw: 0.753399},
    {id: 4, x: 0.526227, y: 2.211401, z: -0.030423, qx: 0.668465, qy: -0.010406, qz: -0.009038, qw: 0.743616},
    {id: 7, x: 1.215298, y: 0.601079, z: 0.032383, qx: 0.558610, qy: -0.345883, qz: -0.394824, qw: 0.642210},
    # {id: 7, x: 0.0, y: 0.0, z: 0.0, qx: 0.0, qy: 0.0, qz: 0.0, qw: 1.0},
    {id: 8, x: 0.873, y: -1.957, z: 0.086, qx: 0.055, qy: 0.658, qz: 0.749, qw: 0.063}
  ]
max_detection_dist: 1.5     # maximum detection distance between tag and camera, recommend < 2.0
max_linear_vel_x: 0.5       # maximum linear velocity for reset pose, max: 1.0, recommend < 0.5 
max_angular_vel_z: 0.5      # maximum angular velocity for reset pose, max: 2.0, recommend < 0.5
xy_tolerance: 0.3           # xy tolerance for reset pose, recommend > 0.3
yaw_tolerance: 0.3          # yaw tolerance for reset pose, recommend > 0.3
image_width: 640
image_height: 480
continuous_check: 5         # ignore fluctuated tag detections, recommend 5 to 10 
check_threshold: 0.15       # threshold for determine the detection is fluctuated or not, recommend 0.15 to 0.5 * xy/yaw_tolerance 
